[2024-04-21T11:04:28.896+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing.get_data_pound scheduled__2024-04-07T00:00:00+00:00 [queued]>
[2024-04-21T11:04:29.050+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing.get_data_pound scheduled__2024-04-07T00:00:00+00:00 [queued]>
[2024-04-21T11:04:29.064+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-21T11:04:29.339+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_data_pound> on 2024-04-07 00:00:00+00:00
[2024-04-21T11:04:29.371+0000] {standard_task_runner.py:60} INFO - Started process 2515 to run task
[2024-04-21T11:04:29.442+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing', 'get_data_pound', 'scheduled__2024-04-07T00:00:00+00:00', '--job-id', '1976', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_parsing.py', '--cfg-path', '/tmp/tmpxhzwa8u9']
[2024-04-21T11:04:29.465+0000] {standard_task_runner.py:88} INFO - Job 1976: Subtask get_data_pound
[2024-04-21T11:04:29.667+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing.get_data_pound scheduled__2024-04-07T00:00:00+00:00 [running]> on host e671688b1343
[2024-04-21T11:04:30.159+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-21T11:04:30.476+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing' AIRFLOW_CTX_TASK_ID='get_data_pound' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-07T00:00:00+00:00'
[2024-04-21T11:04:31.436+0000] {python.py:202} INFO - Done. Returned value was: ([['AUD', 1.9207436279, '2024-4-6'], ['BGN', 2.2711474217, '2024-4-6'], ['BRL', 6.4031694885, '2024-4-6'], ['CAD', 1.7170860157, '2024-4-6'], ['CHF', 1.139858166, '2024-4-6'], ['CNY', 9.1368625925, '2024-4-6'], ['CZK', 29.46097709, '2024-4-6'], ['DKK', 8.6961688808, '2024-4-6'], ['EUR', 1.1657292228, '2024-4-6'], ['GBP', 1, '2024-4-6'], ['HKD', 9.8904736262, '2024-4-6'], ['HRK', 8.4654521748, '2024-4-6'], ['HUF', 454.6321934325, '2024-4-6'], ['IDR', 19990.5198973418, '2024-4-6'], ['ILS', 4.7545846095, '2024-4-6'], ['INR', 105.232585396, '2024-4-6'], ['ISK', 175.235290496, '2024-4-6'], ['JPY', 191.6172411505, '2024-4-6'], ['KRW', 1705.5232670115, '2024-4-6'], ['MXN', 20.8690131146, '2024-4-6'], ['MYR', 5.9949193909, '2024-4-6'], ['NOK', 13.5573465605, '2024-4-6'], ['NZD', 2.1011715611, '2024-4-6'], ['PHP', 71.3813129209, '2024-4-6'], ['PLN', 4.9906346632, '2024-4-6'], ['RON', 5.791425571, '2024-4-6'], ['RUB', 116.8355294348, '2024-4-6'], ['SEK', 13.4425511745, '2024-4-6'], ['SGD', 1.7028549308, '2024-4-6'], ['THB', 46.4507149117, '2024-4-6'], ['TRY', 40.4970358234, '2024-4-6'], ['USD', 1.2638547794, '2024-4-6'], ['ZAR', 23.5579033526, '2024-4-6']], ['title', 'rate', 'date'])
[2024-04-21T11:04:31.618+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=currency_parsing, task_id=get_data_pound, execution_date=20240407T000000, start_date=20240421T110428, end_date=20240421T110431
[2024-04-21T11:04:31.760+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-21T11:04:32.199+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-27T12:19:04.304+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing.get_data_pound scheduled__2024-04-07T00:00:00+00:00 [queued]>
[2024-04-27T12:19:05.188+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing.get_data_pound scheduled__2024-04-07T00:00:00+00:00 [queued]>
[2024-04-27T12:19:05.204+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-27T12:19:07.811+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_data_pound> on 2024-04-07 00:00:00+00:00
[2024-04-27T12:19:08.141+0000] {standard_task_runner.py:60} INFO - Started process 1917 to run task
[2024-04-27T12:19:08.328+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing', 'get_data_pound', 'scheduled__2024-04-07T00:00:00+00:00', '--job-id', '2314', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_parsing.py', '--cfg-path', '/tmp/tmp6orema78']
[2024-04-27T12:19:08.508+0000] {standard_task_runner.py:88} INFO - Job 2314: Subtask get_data_pound
[2024-04-27T12:19:13.908+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing.get_data_pound scheduled__2024-04-07T00:00:00+00:00 [running]> on host 65a8688265d1
[2024-04-27T12:19:18.725+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-27T12:19:26.052+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing' AIRFLOW_CTX_TASK_ID='get_data_pound' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-07T00:00:00+00:00'
[2024-04-27T12:19:47.257+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1073, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.freecurrencyapi.com', port=443): Max retries exceeded with url: /v1/historical?date=2024-04-06&base_currency=GBP&currencies= (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stage/currency_parsing.py", line 14, in get_data_pound
    currencies_list = get_currency_list(execution_date, 'GBP')
  File "/opt/airflow/dags/stage/currency_utils.py", line 21, in get_currency_list
    data = client.historical(f'{year}-{int(month):02d}-{int(day):02d}', base_currency=base_currency)
  File "/home/airflow/.local/lib/python3.8/site-packages/freecurrencyapi/client.py", line 32, in historical
    return self._request('/historical', params={
  File "/home/airflow/.local/lib/python3.8/site-packages/everapi/client.py", line 43, in _request
    response = requests.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.freecurrencyapi.com', port=443): Max retries exceeded with url: /v1/historical?date=2024-04-06&base_currency=GBP&currencies= (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))
[2024-04-27T12:19:47.507+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_parsing, task_id=get_data_pound, execution_date=20240407T000000, start_date=20240427T121904, end_date=20240427T121947
[2024-04-27T12:19:47.735+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2314 for task get_data_pound (HTTPSConnectionPool(host='api.freecurrencyapi.com', port=443): Max retries exceeded with url: /v1/historical?date=2024-04-06&base_currency=GBP&currencies= (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))); 1917)
[2024-04-27T12:19:47.920+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-27T12:19:48.039+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-27T12:19:48.217+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
