[2024-04-21T11:05:51.139+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing.get_data_pound scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-21T11:05:51.301+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing.get_data_pound scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-21T11:05:51.323+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-21T11:05:51.742+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_data_pound> on 2024-04-15 00:00:00+00:00
[2024-04-21T11:05:51.755+0000] {standard_task_runner.py:60} INFO - Started process 2703 to run task
[2024-04-21T11:05:51.822+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing', 'get_data_pound', 'scheduled__2024-04-15T00:00:00+00:00', '--job-id', '2062', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_parsing.py', '--cfg-path', '/tmp/tmpgnfh_qua']
[2024-04-21T11:05:51.904+0000] {standard_task_runner.py:88} INFO - Job 2062: Subtask get_data_pound
[2024-04-21T11:05:52.523+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing.get_data_pound scheduled__2024-04-15T00:00:00+00:00 [running]> on host e671688b1343
[2024-04-21T11:05:52.970+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-21T11:05:53.227+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing' AIRFLOW_CTX_TASK_ID='get_data_pound' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-15T00:00:00+00:00'
[2024-04-21T11:05:54.896+0000] {python.py:202} INFO - Done. Returned value was: ([['AUD', 1.9244027034, '2024-4-14'], ['BGN', 2.2788475665, '2024-4-14'], ['BRL', 6.3828214502, '2024-4-14'], ['CAD', 1.7145225484, '2024-4-14'], ['CHF', 1.1386199145, '2024-4-14'], ['CNY', 9.0088729793, '2024-4-14'], ['CZK', 29.63843803, '2024-4-14'], ['DKK', 8.7289536919, '2024-4-14'], ['EUR', 1.1700502028, '2024-4-14'], ['GBP', 1, '2024-4-14'], ['HKD', 9.7644346603, '2024-4-14'], ['HRK', 8.465522678, '2024-4-14'], ['HUF', 459.2160744917, '2024-4-14'], ['IDR', 19705.4892862707, '2024-4-14'], ['ILS', 4.6474870451, '2024-4-14'], ['INR', 103.9684740867, '2024-4-14'], ['ISK', 176.1268049351, '2024-4-14'], ['JPY', 191.0218667176, '2024-4-14'], ['KRW', 1716.2977696723, '2024-4-14'], ['MXN', 20.6932984637, '2024-4-14'], ['MYR', 5.9387219415, '2024-4-14'], ['NOK', 13.5396616654, '2024-4-14'], ['NZD', 2.0959982886, '2024-4-14'], ['PHP', 70.3799188147, '2024-4-14'], ['PLN', 5.0077764182, '2024-4-14'], ['RON', 5.8188080544, '2024-4-14'], ['RUB', 116.1615265948, '2024-4-14'], ['SEK', 13.5300661484, '2024-4-14'], ['SGD', 1.6949938899, '2024-4-14'], ['THB', 45.5961039083, '2024-4-14'], ['TRY', 40.3701826666, '2024-4-14'], ['USD', 1.2462454912, '2024-4-14'], ['ZAR', 23.4935141306, '2024-4-14']], ['title', 'rate', 'date'])
[2024-04-21T11:05:55.047+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=currency_parsing, task_id=get_data_pound, execution_date=20240415T000000, start_date=20240421T110551, end_date=20240421T110555
[2024-04-21T11:05:55.252+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-21T11:05:55.413+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-27T12:21:31.562+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing.get_data_pound scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-27T12:21:32.608+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing.get_data_pound scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-27T12:21:32.669+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-27T12:21:35.779+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_data_pound> on 2024-04-15 00:00:00+00:00
[2024-04-27T12:21:35.857+0000] {standard_task_runner.py:60} INFO - Started process 2018 to run task
[2024-04-27T12:21:36.324+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing', 'get_data_pound', 'scheduled__2024-04-15T00:00:00+00:00', '--job-id', '2351', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_parsing.py', '--cfg-path', '/tmp/tmpu7men4m5']
[2024-04-27T12:21:37.157+0000] {standard_task_runner.py:88} INFO - Job 2351: Subtask get_data_pound
[2024-04-27T12:21:42.933+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing.get_data_pound scheduled__2024-04-15T00:00:00+00:00 [running]> on host 65a8688265d1
[2024-04-27T12:21:52.202+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-27T12:21:54.208+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing' AIRFLOW_CTX_TASK_ID='get_data_pound' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-15T00:00:00+00:00'
[2024-04-27T12:22:49.849+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1073, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.freecurrencyapi.com', port=443): Max retries exceeded with url: /v1/historical?date=2024-04-14&base_currency=GBP&currencies= (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stage/currency_parsing.py", line 14, in get_data_pound
    sleep(35)
  File "/opt/airflow/dags/stage/currency_utils.py", line 21, in get_currency_list
    data = client.historical(f'{year}-{int(month):02d}-{int(day):02d}', base_currency=base_currency)
  File "/home/airflow/.local/lib/python3.8/site-packages/freecurrencyapi/client.py", line 32, in historical
    return self._request('/historical', params={
  File "/home/airflow/.local/lib/python3.8/site-packages/everapi/client.py", line 43, in _request
    response = requests.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.freecurrencyapi.com', port=443): Max retries exceeded with url: /v1/historical?date=2024-04-14&base_currency=GBP&currencies= (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))
[2024-04-27T12:22:50.145+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_parsing, task_id=get_data_pound, execution_date=20240415T000000, start_date=20240427T122131, end_date=20240427T122250
[2024-04-27T12:22:50.940+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2351 for task get_data_pound (HTTPSConnectionPool(host='api.freecurrencyapi.com', port=443): Max retries exceeded with url: /v1/historical?date=2024-04-14&base_currency=GBP&currencies= (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))); 2018)
[2024-04-27T12:22:51.073+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-27T12:22:51.120+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-27T12:22:51.562+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
