[2024-05-05T12:41:17.473+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing.run_dbt scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-05T12:41:17.497+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing.run_dbt scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-05T12:41:17.499+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2024-05-05T12:41:17.540+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): run_dbt> on 2024-05-02 00:00:00+00:00
[2024-05-05T12:41:17.549+0000] {standard_task_runner.py:60} INFO - Started process 126 to run task
[2024-05-05T12:41:17.557+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing', 'run_dbt', 'scheduled__2024-05-02T00:00:00+00:00', '--job-id', '2753', '--raw', '--subdir', 'DAGS_FOLDER/currency_dag/currency_parsing.py', '--cfg-path', '/tmp/tmph_7j964y']
[2024-05-05T12:41:17.562+0000] {standard_task_runner.py:88} INFO - Job 2753: Subtask run_dbt
[2024-05-05T12:41:17.651+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing.run_dbt scheduled__2024-05-02T00:00:00+00:00 [running]> on host 0b7a5c0943cc
[2024-05-05T12:41:17.802+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-02T00:00:00+00:00'
[2024-05-05T12:41:17.806+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-05T12:41:17.807+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run']
[2024-05-05T12:41:17.837+0000] {subprocess.py:86} INFO - Output:
[2024-05-05T12:41:17.861+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2024-05-05T12:41:17.864+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-05-05T12:41:17.889+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-05-05T12:41:17.898+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_parsing, task_id=run_dbt, execution_date=20240502T000000, start_date=20240505T124117, end_date=20240505T124117
[2024-05-05T12:41:17.985+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2753 for task run_dbt (Bash command failed. The command returned a non-zero exit code 127.; 126)
[2024-05-05T12:41:18.057+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-05T12:41:18.117+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
