[0m20:26:39.519274 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B0071858E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B0070964E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B0071856D0>]}


============================== 20:26:39.529226 | 3df201db-be79-41c3-a5a6-93f14e0f20f5 ==============================
[0m20:26:39.529226 [info ] [MainThread]: Running with dbt=1.7.13
[0m20:26:39.531269 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\almat\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m20:26:39.533228 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': WindowsPath('C:/Users/almat/.dbt')}
[0m20:26:39.534228 [info ] [MainThread]: Creating dbt configuration folder at 
[0m20:28:27.243836 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBDADD5550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBDADD5640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBDADD56A0>]}


============================== 20:28:27.251833 | 21107922-42a1-49d1-95d9-6d0de3fe7c8d ==============================
[0m20:28:27.251833 [info ] [MainThread]: Running with dbt=1.7.13
[0m20:28:27.253835 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\almat\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m20:29:57.337339 [error] [MainThread]: Encountered an error:

[0m20:29:57.341345 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\almat\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 91, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\almat\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\almat\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\main.py", line 515, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\almat\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 322, in run
    project_name = self.get_valid_project_name()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\almat\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 276, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\almat\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\almat\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m20:29:57.346341 [debug] [MainThread]: Command `dbt init` failed at 20:29:57.345338 after 90.21 seconds
[0m20:29:57.347339 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBD4835190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBDA30FE00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBDAA2A780>]}
[0m20:29:57.349337 [debug] [MainThread]: Flushing usage events
[0m20:37:14.561599 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B1B34354C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B1B34355B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B1B3436A20>]}


============================== 20:37:14.569604 | 47fd6da1-6e4b-4801-9317-e24f42a56516 ==============================
[0m20:37:14.569604 [info ] [MainThread]: Running with dbt=1.7.13
[0m20:37:14.571638 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\almat\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:37:14.572599 [info ] [MainThread]: dbt version: 1.7.13
[0m20:37:14.574604 [info ] [MainThread]: python version: 3.12.1
[0m20:37:14.575598 [info ] [MainThread]: python path: C:\Users\almat\AppData\Local\Programs\Python\Python312\python.exe
[0m20:37:14.576639 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m20:37:14.804544 [info ] [MainThread]: Using profiles dir at C:\Users\almat\.dbt
[0m20:37:14.806543 [info ] [MainThread]: Using profiles.yml file at C:\Users\almat\.dbt\profiles.yml
[0m20:37:14.807542 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\almat\OneDrive\Desktop\course\airflow\airflow-project\dbt_project.yml
[0m20:37:14.810545 [info ] [MainThread]: adapter type: postgres
[0m20:37:14.812543 [info ] [MainThread]: adapter version: 1.7.13
[0m20:37:14.814544 [info ] [MainThread]: Configuration:
[0m20:37:14.816541 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m20:37:14.818542 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m20:37:14.819539 [info ] [MainThread]: Required dependencies:
[0m20:37:14.821543 [debug] [MainThread]: Executing "git --help"
[0m20:37:14.878545 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m20:37:14.880554 [debug] [MainThread]: STDERR: "b''"
[0m20:37:14.881545 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m20:37:14.884548 [info ] [MainThread]: Connection:
[0m20:37:14.889779 [info ] [MainThread]:   host: localhost
[0m20:37:14.892289 [info ] [MainThread]:   port: 5432
[0m20:37:14.894625 [info ] [MainThread]:   user: postgres
[0m20:37:14.897409 [info ] [MainThread]:   database: analytics
[0m20:37:14.899305 [info ] [MainThread]:   schema: analytics
[0m20:37:14.902136 [info ] [MainThread]:   connect_timeout: 10
[0m20:37:14.904136 [info ] [MainThread]:   role: None
[0m20:37:14.906144 [info ] [MainThread]:   search_path: None
[0m20:37:14.908138 [info ] [MainThread]:   keepalives_idle: 0
[0m20:37:14.909138 [info ] [MainThread]:   sslmode: None
[0m20:37:14.911138 [info ] [MainThread]:   sslcert: None
[0m20:37:14.912140 [info ] [MainThread]:   sslkey: None
[0m20:37:14.913135 [info ] [MainThread]:   sslrootcert: None
[0m20:37:14.915136 [info ] [MainThread]:   application_name: dbt
[0m20:37:14.916139 [info ] [MainThread]:   retries: 1
[0m20:37:14.917135 [info ] [MainThread]: Registered adapter: postgres=1.7.13
[0m20:37:14.919139 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m20:37:14.920136 [debug] [MainThread]: Using postgres connection "debug"
[0m20:37:14.921136 [debug] [MainThread]: On debug: select 1 as id
[0m20:37:14.922145 [debug] [MainThread]: Opening a new connection, currently in state init
[0m20:37:18.995572 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?

[0m20:37:23.049821 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m20:37:23.050869 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m20:37:23.051829 [debug] [MainThread]: On debug: No close available on handle
[0m20:37:23.052831 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m20:37:23.053837 [info ] [MainThread]: [31m2 checks failed:[0m
[0m20:37:23.055828 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\almat\OneDrive\Desktop\course\airflow\airflow-project\dbt_project.yml> not found

[0m20:37:23.056836 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
  	Is the server running on that host and accepting TCP/IP connections?
  connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
  	Is the server running on that host and accepting TCP/IP connections?
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m20:37:23.059828 [debug] [MainThread]: Command `dbt debug` failed at 20:37:23.059828 after 8.77 seconds
[0m20:37:23.061830 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m20:37:23.062834 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B1B34F64B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B1B3355100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B1B3354FB0>]}
[0m20:37:23.063836 [debug] [MainThread]: Flushing usage events
[0m20:37:46.319949 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000287E2ACD940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000287E2ACDEB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000287E2ACE750>]}


============================== 20:37:46.329947 | 8fc4572d-8e35-4f27-8032-b4419f8b6adf ==============================
[0m20:37:46.329947 [info ] [MainThread]: Running with dbt=1.7.13
[0m20:37:46.331941 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\almat\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m20:37:46.332941 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\almat\OneDrive\Desktop\course\airflow\airflow-project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:37:46.336940 [debug] [MainThread]: Command `dbt run` failed at 20:37:46.336940 after 0.20 seconds
[0m20:37:46.338940 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000287E2737200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000287E20D3A40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000287E2ACFC80>]}
[0m20:37:46.340940 [debug] [MainThread]: Flushing usage events
[0m17:09:15.864021 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EFED514230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EFED514DA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EFED514EC0>]}


============================== 17:09:15.875023 | 163db888-b89e-4117-b665-ed12311d1041 ==============================
[0m17:09:15.875023 [info ] [MainThread]: Running with dbt=1.7.13
[0m17:09:15.877025 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:/Users/almat/OneDrive/Desktop/course/airflow/airflow-project/dags/currency_dag/dbt_currency', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --profiles-dir C:/Users/almat/OneDrive/Desktop/course/airflow/airflow-project/dags/currency_dag/dbt_currency', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:09:15.878023 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\almat\OneDrive\Desktop\course\airflow\airflow-project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:09:15.881026 [debug] [MainThread]: Command `dbt run` failed at 17:09:15.881026 after 0.33 seconds
[0m17:09:15.882023 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EFED514DA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EFED514FE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EFED514230>]}
[0m17:09:15.884025 [debug] [MainThread]: Flushing usage events
[0m17:19:41.365963 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC5A385820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC5A3862A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC5A384AA0>]}


============================== 17:19:41.378974 | d37aeb0d-4032-45d2-8d07-cf2deca0ca07 ==============================
[0m17:19:41.378974 [info ] [MainThread]: Running with dbt=1.7.13
[0m17:19:41.381962 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:/Users/almat/OneDrive/Desktop/course/airflow/airflow-project/dags/currency_dag/dbt_currency', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --profiles-dir C:/Users/almat/OneDrive/Desktop/course/airflow/airflow-project/dags/currency_dag/dbt_currency', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:19:41.383973 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\almat\OneDrive\Desktop\course\airflow\airflow-project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:19:41.386967 [debug] [MainThread]: Command `dbt run` failed at 17:19:41.385964 after 0.40 seconds
[0m17:19:41.388962 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC5A135B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC5A0254F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC5A1B5D00>]}
[0m17:19:41.390969 [debug] [MainThread]: Flushing usage events
[0m17:21:00.848429 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C69F77F170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C69F9D5AC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C69F9D6A50>]}


============================== 17:21:00.855428 | ea773058-dc26-4814-ba39-449977274094 ==============================
[0m17:21:00.855428 [info ] [MainThread]: Running with dbt=1.7.13
[0m17:21:00.857428 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\almat\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m17:21:00.858433 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\almat\OneDrive\Desktop\course\airflow\airflow-project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:21:00.862427 [debug] [MainThread]: Command `dbt run` failed at 17:21:00.862427 after 0.33 seconds
[0m17:21:00.864429 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C69F9F6C60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C69F9F6A80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C69F9F5850>]}
[0m17:21:00.865431 [debug] [MainThread]: Flushing usage events
[0m18:09:02.349696 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F193257F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F193273B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F19327200>]}


============================== 18:09:02.358694 | 86b1c2fb-b23b-4b11-909e-786bb0f162a0 ==============================
[0m18:09:02.358694 [info ] [MainThread]: Running with dbt=1.7.13
[0m18:09:02.360696 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\almat\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:09:02.363695 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\almat\OneDrive\Desktop\course\airflow\airflow-project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:09:02.366697 [debug] [MainThread]: Command `dbt run` failed at 18:09:02.366697 after 0.31 seconds
[0m18:09:02.367698 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F19345250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F19346690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F19345B20>]}
[0m18:09:02.369696 [debug] [MainThread]: Flushing usage events
