[2024-04-20T13:11:50.231+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing_rub.fetch_data manual__2024-04-20T12:27:38.212240+00:00 [queued]>
[2024-04-20T13:11:50.258+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing_rub.fetch_data manual__2024-04-20T12:27:38.212240+00:00 [queued]>
[2024-04-20T13:11:50.259+0000] {taskinstance.py:2193} INFO - Starting attempt 5 of 6
[2024-04-20T13:11:50.665+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-04-20 12:27:38.212240+00:00
[2024-04-20T13:11:50.674+0000] {standard_task_runner.py:60} INFO - Started process 307 to run task
[2024-04-20T13:11:50.682+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing_rub', 'fetch_data', 'manual__2024-04-20T12:27:38.212240+00:00', '--job-id', '832', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_rub.py', '--cfg-path', '/tmp/tmp0b6twvzr']
[2024-04-20T13:11:50.685+0000] {standard_task_runner.py:88} INFO - Job 832: Subtask fetch_data
[2024-04-20T13:11:50.776+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing_rub.fetch_data manual__2024-04-20T12:27:38.212240+00:00 [running]> on host 31aa6d9ea6ff
[2024-04-20T13:11:50.931+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing_rub' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T12:27:38.212240+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-20T12:27:38.212240+00:00'
[2024-04-20T13:11:50.980+0000] {base.py:83} INFO - Using connection ID 'dwh' for task execution.
[2024-04-20T13:11:50.991+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stage/currency_rub.py", line 33, in fetch_data
    dwh_hook.insert_rows(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 565, in insert_rows
    cur.execute(sql, values)
psycopg2.errors.UndefinedColumn: column "numcode" of relation "currency_parsing_rub" does not exist
LINE 1: INSERT INTO stage.currency_parsing_rub (ID, NumCode, CharCod...
                                                    ^

[2024-04-20T13:11:51.017+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_parsing_rub, task_id=fetch_data, execution_date=20240420T122738, start_date=20240420T131150, end_date=20240420T131151
[2024-04-20T13:11:51.042+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 832 for task fetch_data (column "numcode" of relation "currency_parsing_rub" does not exist
LINE 1: INSERT INTO stage.currency_parsing_rub (ID, NumCode, CharCod...
                                                    ^
; 307)
[2024-04-20T13:11:51.056+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-20T13:11:51.094+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
