[2024-04-20T13:30:05.540+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_parsing_kzt.fetch_data_22 scheduled__2024-04-19T00:00:00+00:00 [queued]>
[2024-04-20T13:30:05.553+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_parsing_kzt.fetch_data_22 scheduled__2024-04-19T00:00:00+00:00 [queued]>
[2024-04-20T13:30:05.554+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-20T13:30:05.577+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): fetch_data_22> on 2024-04-19 00:00:00+00:00
[2024-04-20T13:30:05.583+0000] {standard_task_runner.py:60} INFO - Started process 589 to run task
[2024-04-20T13:30:05.588+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'currency_parsing_kzt', 'fetch_data_22', 'scheduled__2024-04-19T00:00:00+00:00', '--job-id', '845', '--raw', '--subdir', 'DAGS_FOLDER/stage/currency_kzt.py', '--cfg-path', '/tmp/tmpnrrvtm9j']
[2024-04-20T13:30:05.592+0000] {standard_task_runner.py:88} INFO - Job 845: Subtask fetch_data_22
[2024-04-20T13:30:05.665+0000] {task_command.py:423} INFO - Running <TaskInstance: currency_parsing_kzt.fetch_data_22 scheduled__2024-04-19T00:00:00+00:00 [running]> on host 31aa6d9ea6ff
[2024-04-20T13:30:05.786+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='currency_parsing_kzt' AIRFLOW_CTX_TASK_ID='fetch_data_22' AIRFLOW_CTX_EXECUTION_DATE='2024-04-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-19T00:00:00+00:00'
[2024-04-20T13:30:05.805+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stage/currency_kzt.py", line 34, in fetch_data
    rows, fields = transformed_data
TypeError: cannot unpack non-iterable NoneType object
[2024-04-20T13:30:05.823+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=currency_parsing_kzt, task_id=fetch_data_22, execution_date=20240419T000000, start_date=20240420T133005, end_date=20240420T133005
[2024-04-20T13:30:05.840+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 845 for task fetch_data_22 (cannot unpack non-iterable NoneType object; 589)
[2024-04-20T13:30:05.880+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-20T13:30:05.907+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
